name: "Publish rust binaries"

on:
  workflow_dispatch:
    inputs:
      build_secret:
        type: string
        description: Build secret
jobs:
  check-user-permissions:
    runs-on: ubuntu-latest
    steps:
      - name: Check user permission
        uses: stjude/proteinpaint/.github/actions/check-user-permissions@new-workflows
        with:
          BUILD_SECRET: ${{ secrets.BUILD_SECRET }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          INPUT_BUILD_SECRET: ${{ github.event.inputs.build_secret }}
