name: "Publish docker image"

on:
  workflow_dispatch:
    inputs:
      build_secret:
        type: string
        description: Build secret
jobs:
  check-user-permissions:
    runs-on: ubuntu-latest
    steps:
      - name: Check user permission
        uses: stjude/proteinpaint/.github/actions/check-user-permissions@new-workflows
        with:
          BUILD_SECRET: ${{ secrets.BUILD_SECRET }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          INPUT_BUILD_SECRET: ${{ github.event.inputs.build_secret }}

  build-docker-image:
    needs: check-user-permissions
    runs-on: ubuntu-latest
    steps:
      - name: Publish docker image
        uses: stjude/proteinpaint/.github/actions/publish-docker@master
        with:
          PAT: ${{ secrets.PAT }}
          GITHUB_ACTOR: ${{ github.actor }}